# Generated by Django 3.2.4 on 2021-08-11 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Neuron",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="The unique name of the worm neuron",
                        max_length=10,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "neuron",
                "verbose_name_plural": "neurons",
                "ordering": ["name"],
            },
        ),
    ]
